server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取服务实例列表间隔
  instance:
    lease-expiration-duration-in-seconds: 20  #20s没有服务续约eureka认定该服务失效
    lease-renewal-interval-in-seconds: 5  #服务续约间隔
zuul:
  prefix: /api     #网关前缀
  routes:
    item-service: /item/**  # 路由到商品的微服务
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    search-service: /search/** # es的索引库路由
leyou:
  cors:
    allowed-origin:
      - Http://manage.leyou.com
    allowed-method:
      - OPTIONS
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - HEAD