server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取服务实例列表间隔
  instance:
    lease-expiration-duration-in-seconds: 20  #20s没有服务续约eureka认定该服务失效
    lease-renewal-interval-in-seconds: 5  #服务续约间隔
zuul:
  prefix: /api     #网关前缀
  routes:
    item-service: /item/**  # 路由到商品微服务
    user-service: /user/** # 路由到用户微服务
    search-service: /search/** # 路由到搜索微服务
    auth-service: /auth/** # 路由的授权中心微服务
    cart-service: /cart/** # 路由到购物车微服务
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true  # 路由时携带请求主机的标识的头部
  sensitive-headers:       # 指定响应时过滤的头信息，这里设置为不过滤任何响应头

leyou:
  cors:
    allowed-origin:
      - Http://manage.leyou.com
      - Http://www.leyou.com
      - http://127.0.0.1:9002
    allowed-method:
      - OPTIONS
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - HEAD
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
  jwt:
    cookie-name: LY_TOKEN
    public-key-path: D:\javaother\rsa\rsa.pub