server:
  port: 8084
spring:
  application:
    name: leyou-page
  thymeleaf:
    cache: false  # 开发阶段关闭thymeleaf缓存，不用重启服务只需rebuild即可看到页面更新效果
  rabbitmq:
    host: 192.168.126.129
    username: root
    password: root
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}