server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///ssm
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #服务续约间隔
    lease-expiration-duration-in-seconds: 15  #服务失效时间
mybatis:
  type-aliases-package:  com.item.leyou.domain